import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Abdul Rahman",
  description: "I'm a Developer from Pakistan. Welcome to my Portfolio. ",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Abdul Rahman</title>
        <meta
          name="description"
          content="I'm a Developer from Pakistan. Welcome to my Portfolio."
        />
        <meta name="keywords" content="Next.js, React, Portfolio" />
        <meta name="author" content="Your Name" />
        <meta property="og:title" content="Create Next App" />
        <meta
          property="og:description"
          content="Generated by create next app"
        />
        <meta property="og:image" content="link-to-your-image" />
        <meta property="og:url" content="your-website-url" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
